name: Unit Tests
on:
  push:
    branches:
      - dev
    paths:
      - "src/**"
  pull_request:
    branches:
      - dev
    paths:
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v3
      - name: Run Tests
        run: |
          cd src
          python3 -m unittest discover -s tests -p 'test_*.py'
